name: FAIMER E2E Tests

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose test environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Install Playwright browsers
        run: npx playwright install chromium

      - name: Run E2E tests
        env:
          TEST_ENVIRONMENT: '${{ github.event.inputs.environment }}'
          KEYCLOAK_USERNAME: '${{ secrets.KEYCLOAK_USERNAME }}'
          KEYCLOAK_PASSWORD: '${{ secrets.KEYCLOAK_PASSWORD }}'
        run: npm run faimer-e2e

      - name: Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
