name: FAIMER E2E Tests

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose test environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Install Playwright browsers
        run: npx playwright install chromium

      - name: Update test list in README
        if: github.event_name == 'push'
        id: update_readme
        run: npm run update-test-list

      - name: Commit and push updated README
        if: github.event_name == 'push' && steps.update_readme.outputs.readme_updated == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update test list in README"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run E2E tests
        env:
          TEST_ENVIRONMENT: '${{ github.event.inputs.environment }}'
          O3_URL_DEV: '${{ vars.O3_URL_DEV }}'
          O3_URL_QA: '${{ vars.O3_URL_QA }}'
          KEYCLOAK_URL_DEV: '${{ vars.KEYCLOAK_URL_DEV }}'
          KEYCLOAK_URL_QA: '${{ vars.KEYCLOAK_URL_QA }}'
          IFRAME_URL_DEV: '${{ vars.IFRAME_URL_DEV }}'
          IFRAME_URL_QA: '${{ vars.IFRAME_URL_QA }}'
          KEYCLOAK_USERNAME: '${{ secrets.KEYCLOAK_USERNAME }}'
          KEYCLOAK_PASSWORD: '${{ secrets.KEYCLOAK_PASSWORD }}'
        run: npm run faimer-e2e

      - name: Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
